eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost
spring:
  application:
    name: comment-user
  data:
    mongodb:
      database: comment_db
      port: 27017
  cloud:
    discovery:
      enabled: true
server:
  port: 3015
management:
  endpoints:
    web:
      exposure:
        include: '*'





